import { TraitsProps } from "../store/trait";


export * from "./Offer";
export * from "./Token";

type EventGuid = {
  creation_number: string;
  account_address: string;
};

type Event = {
  guid: EventGuid;
  sequence_number: string;
  type: string;
  /**
   * The JSON representation of the event
   */
  data: TraitsProps;
};

export type UserTransactionResponse = {
  version: string;
  hash: string;
  state_change_hash: string;
  event_root_hash: string;
  state_checkpoint_hash: string | null;
  gas_used: string;
  /**
   * Whether the transaction was successful
   */
  success: boolean;
  /**
   * The VM status of the transaction, can tell useful information in a failure
   */
  vm_status: string;
  accumulator_root_hash: string;
  /**
   * Final state of resources changed by the transaction
   */
  sender: string;
  sequence_number: string;
  max_gas_amount: string;
  gas_unit_price: string;
  expiration_timestamp_secs: string;

  /**
   * Events generated by the transaction
   */
  events: Array<Event>;
  timestamp: string;
};
